codecov:
  notify:
    require_ci_to_pass: false
    after_n_builds: 1
    wait_for_ci: false
  allow_coverage_offsets: true

  bot: aurorafoss

coverage:
  precision: 3
  round: down
  range: "80...100"
  status:
    project:
      default:
        # basic
        target: auto
        threshold: null
        base: auto 
        # advanced
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null
    patch:
      default:
        informational: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true  # if true: only post the comment if coverage changes
  require_base: no
  require_head: yes
  branches: null