image: aurorafossorg/archlinux:latest

stages:
  - check
  - build
  - test
  - deploy

# Style checker
codestyle:
  stage: check
  image: aurorafossorg/dlang:latest
  script: dscanner -S .

# Syntax check before compilation
syntax_check:
  stage: check
  image: aurorafossorg/dlang:latest
  script: dscanner -s .

# Indentation check according to editorconfig file
editorconfig:
  stage: check
  image: node:latest
  cache:
    paths:
      - node_modules/
  script:
    - npm install eclint
    - npx eclint check "src/**/*.d" "*.json" "**/meson.build" "*.yml"

.artifacts_template: &artifacts_definition
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - .out/bin/

.linux-dub_template: &linux-dub_definition
  cache:
    paths:
      - .dub/
  image: aurorafossorg/dlang:latest
  script:
    - ./tools/dub.sh $BUILD_DUB_FLAGS

.x86_64-linux-deps_template: &x86_64-linux-deps_definition
  before_script:
    - pacman -Sy libsndfile --noconfirm

.x86-linux-deps_template: &x86-linux-deps_definition
  before_script:
    - pacman -Sy lib32-libsndfile --noconfirm

x86_64-linux-dub-dmd-debug:
  stage: build
  <<: *artifacts_definition
  <<: *linux-dub_definition
  <<: *x86_64-linux-deps_definition
  variables:
    BUILD_DUB_FLAGS: $CI_JOB_STAGE --arch=x86_64 --compiler=dmd

x86-linux-dub-dmd-debug:
  stage: build
  <<: *artifacts_definition
  <<: *linux-dub_definition
  <<: *x86-linux-deps_definition
  variables:
    BUILD_DUB_FLAGS: $CI_JOB_STAGE --arch=x86 --compiler=dmd

x86_64-linux-dub-ldc-debug:
  stage: build
  <<: *artifacts_definition
  <<: *linux-dub_definition
  <<: *x86_64-linux-deps_definition
  variables:
    BUILD_DUB_FLAGS: $CI_JOB_STAGE --arch=x86_64 --compiler=ldc

x86-linux-dub-ldc-debug:
  stage: build
  <<: *artifacts_definition
  <<: *linux-dub_definition
  <<: *x86-linux-deps_definition
  variables:
    BUILD_DUB_FLAGS: $CI_JOB_STAGE --arch=x86 --compiler=ldc

code_coverage:
  stage: test
  <<: *linux-dub_definition
  <<: *x86_64-linux-deps_definition
  variables:
    BUILD_DUB_FLAGS: $CI_JOB_STAGE --build=unittest-cov
  after_script:
    - bash <(curl -s https://codecov.io/bash)
