language: d

sudo: required

d:
  - dmd
  - ldc
  - gdc
  - dmd-nightly
  - dmd-beta
  - ldc-beta

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    d:
      - gdc
      - dmd-nightly
      - dmd-beta
      - ldc-beta
    os:
      - osx

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
    - libx11-dev
    - git
    - cmake
    - gcc-7
    - g++-7

env: CC=gcc-7 CXX=g++-7

before_script:
  - brew install gcc@7
  - mkdir -p .tmp && pushd .tmp
  - git clone https://github.com/andrewrk/libsoundio && pushd libsoundio
  - mkdir -p build && pushd build
  - cmake ..
  - make
  - sudo make install
  - popd; popd; popd;
  - sudo ldconfig

