#                                     __
#                                    / _|
#   __ _ _   _ _ __ ___  _ __ __ _  | |_ ___  ___ ___
#  / _` | | | | '__/ _ \| '__/ _` | |  _/ _ \/ __/ __|
# | (_| | |_| | | | (_) | | | (_| | | || (_) \__ \__ \
#  \__,_|\__,_|_|  \___/|_|  \__,_| |_| \___/|___/___/
#
# Copyright (C) 2018-2019 Aurora Free Open Source Software.
#
# This file is part of the Aurora Free Open Source Software. This
# organization promote free and open source software that you can
# redistribute and/or modify under the terms of the GNU Lesser General
# Public License Version 3 as published by the Free Software Foundation or
# (at your option) any later version approved by the Aurora Free Open Source
# Software Organization. The license is available in the package root path
# as 'LICENSE' file. Please review the following information to ensure the
# GNU Lesser General Public License version 3 requirements will be met:
# https://www.gnu.org/licenses/lgpl.html .
#
# Alternatively, this file may be used under the terms of the GNU General
# Public License version 3 or later as published by the Free Software
# Foundation. Please review the following information to ensure the GNU
# General Public License requirements will be met:
# http://www.gnu.org/licenses/gpl-3.0.html.
#
# NOTE: All products, services or anything associated to trademarks and
# service marks used or referenced on this file are the property of their
# respective companies/owners or its subsidiaries. Other names and brands
# may be claimed as the property of others.
#
# For more info about intellectual property visit: aurorafoss.org or
# directly send an email to: contact (at) aurorafoss.org .

language: d

# More about OSX Environment here: https://docs.travis-ci.com/user/reference/osx
os: osx

# Test on different macOS versions
osx_image:
  - xcode11.3 # Latest macOS 10.14
  - xcode10.3 # macOS 10.14.4
  - xcode10.1 # Latest macOS 10.13
  - xcode9.4 # Default, macOS 10.13
  - xcode9.2 # Latest macOS 10.12
# Not supported versions
#  - xcode8 # Latest macOS 10.11
#  - xcode6.4 # Latest macOS 10.10

d:
  - dmd
  - ldc
  - dmd-nightly
  - ldc-latest-ci
  - dmd-beta
  - ldc-beta
# Not supported by macOS
#  - gdc

jobs:
  fast_finish: true
  allow_failures:
  - d: dmd-nightly
  - d: ldc-latest-ci
  - d: dmd-beta
  - d: ldc-beta
# Not supported by macOS
#  - d: gdc

before_script:
  - brew install libsndfile libsoundio

script:
  - ./tools/dub.sh build --compiler=${DC}
  - ./tools/dub.sh test --compiler=${DC}
  - ./tools/do-examples.sh --compiler=${DC}
