#                                     __
#                                    / _|
#   __ _ _   _ _ __ ___  _ __ __ _  | |_ ___  ___ ___
#  / _` | | | | '__/ _ \| '__/ _` | |  _/ _ \/ __/ __|
# | (_| | |_| | | | (_) | | | (_| | | || (_) \__ \__ \
#  \__,_|\__,_|_|  \___/|_|  \__,_| |_| \___/|___/___/
#
# Copyright (C) 2018-2019 Aurora Free Open Source Software.
#
# This file is part of the Aurora Free Open Source Software. This
# organization promote free and open source software that you can
# redistribute and/or modify under the terms of the GNU Lesser General
# Public License Version 3 as published by the Free Software Foundation or
# (at your option) any later version approved by the Aurora Free Open Source
# Software Organization. The license is available in the package root path
# as 'LICENSE' file. Please review the following information to ensure the
# GNU Lesser General Public License version 3 requirements will be met:
# https://www.gnu.org/licenses/lgpl.html .
#
# Alternatively, this file may be used under the terms of the GNU General
# Public License version 3 or later as published by the Free Software
# Foundation. Please review the following information to ensure the GNU
# General Public License requirements will be met:
# http://www.gnu.org/licenses/gpl-3.0.html.
#
# NOTE: All products, services or anything associated to trademarks and
# service marks used or referenced on this file are the property of their
# respective companies/owners or its subsidiaries. Other names and brands
# may be claimed as the property of others.
#
# For more info about intellectual property visit: aurorafoss.org or
# directly send an email to: contact (at) aurorafoss.org .

language: d

sudo: required

d:
  - dmd
  - ldc
  - dmd-nightly
  - dmd-beta
  - ldc-beta

os:
  - linux
  - osx

matrix:
  include:
    - d: dmd
      env: [COVERAGE=true]
      script: ./tools/dub.sh test -b unittest-cov --compiler=${DC}
    - os: linux
      d: gdc
  fast_finish: true
  allow_failures:
    - os: osx
    - d: gdc
    - d: dmd-nightly
    - d: dmd-beta
    - d: ldc-beta

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
    - libx11-dev
    - git
    - cmake
    - gcc-7
    - g++-7
    - libsndfile1-dev
    - jack

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC=gcc-7; export CXX=g++-7; fi;
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libsndfile; brew upgrade cmake; fi;
  - mkdir -p .tmp && pushd .tmp
  - git clone https://github.com/andrewrk/libsoundio && pushd libsoundio
  - mkdir -p build && pushd build
  - cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr -D CMAKE_INSTALL_LIBDIR=lib -D BUILD_EXAMPLE_PROGRAMS=OFF -D BUILD_TESTS=OFF -D BUILD_STATIC_LIBS=OFF -D ENABLE_JACK=ON ..
  - make
  - sudo make install
  - popd; popd; popd;
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ldconfig; fi;

after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
  - if [[ "$COVERAGE" == true ]]; then bash <(curl -s https://codecov.io/bash); fi;

after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
