language: d

sudo: required

addons:
  apt:
    update: true
    packages:
    - libx11-dev
    - git
    - cmake

before_script:
  - mkdir -p .tmp && pushd .tmp
  - git clone https://github.com/andrewrk/libsoundio && pushd libsoundio
  - mkdir -p build pushd build
  - cmake ..
  - make
  - sudo make install
  - popd; popd; popd;

d:
  - dmd
  - ldc
  - gdc
  - dmd-nightly
  - dmd-beta
  - ldc-beta

os:
  - linux
  - osx

