language: d

sudo: required

d:
  - dmd
  - ldc
  - gdc
  - dmd-nightly
  - dmd-beta
  - ldc-beta

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - d: gdc
    - d: dmd-nightly
    - d: dmd-beta
    - d: ldc-beta

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
    - libx11-dev
    - git
    - cmake
    - gcc-7
    - g++-7
    - libsndfile1-dev

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC=gcc-7; export CXX=g++-7; fi;
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libsndfile; brew upgrade cmake; fi;
  - mkdir -p .tmp && pushd .tmp
  - git clone https://github.com/andrewrk/libsoundio && pushd libsoundio
  - mkdir -p build && pushd build
  - cmake ..
  - make
  - sudo make install
  - popd; popd; popd;
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ldconfig; fi;

after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL