language: d

sudo: required

d:
  - dmd
  - ldc
  - gdc
  - dmd-nightly
  - dmd-beta
  - ldc-beta

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    d:
      - gdc
      - dmd-nightly
      - dmd-beta
      - ldc-beta
    os:
      - osx

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
    - libx11-dev
    - git
    - cmake
    - gcc-7
    - g++-7

env: CC=gcc-7 CXX=g++-7

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then; brew install gcc@7; fi;
  - mkdir -p .tmp && pushd .tmp
  - git clone https://github.com/andrewrk/libsoundio && pushd libsoundio
  - mkdir -p build && pushd build
  - cmake ..
  - make
  - sudo make install
  - popd; popd; popd;
  - sudo ldconfig

after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL